### ISSUE TITLE
When using offset, there is a jump at the end of the animation to the actual element

### ISSUE THREAD

**Issue by roarkmccolgan** [Yuliang-Lee/v-smooth-scroll#7]
Hi,

Thanks for the great package,
I am using offset with the idea that it would stop (i.e. -50px) before the element I'm scrolling too.
However at the end of the animation when it reaches (-50px from element) it snaps to the actual element position (disregarding offset) 

Do you know how I can prevent this?

Thanks!

**Comment by Yuliang-Lee** [comment]
look follow demo code
https://codesandbox.io/s/epic-sid-z5tp1b?file=/src/components/HelloWorld.vue:2677-2690
