### ISSUE TITLE
Vue 3 programmatic usage of v-smooth-scroll not working

### ISSUE THREAD

**Issue by roenfeldt** [Yuliang-Lee/v-smooth-scroll#8]
First off, thank you @Yuliang-Lee  for this great package!

Could you provide an example of the programmatic usage of the package for Vue 3? I tried the Vue 2 version, but of course it won't work.

Thank you!

```js
// this code outputs the "Uncaught TypeError: this is undefined" error in the console
const myEl = this.$refs.myEl || this.$el || document.getElementById(...)

this.$smoothScroll({
  scrollTo: myEl,
  hash: '#sampleHash'  // required if updateHistory is true
})
```

**Comment by Yuliang-Lee** [comment]
please show more infomation or give a reproduce demo like https://codesandbox.io/s/epic-sid-z5tp1b?file=/src/components/HelloWorld.vue

**Comment by roenfeldt** [comment]
@Yuliang-Lee apologies for not being specific enough. What I meant, was that I needed an example of programatically triggering smooth scrolling when using Vue 3 **and** the Composition API.

I [forked your demo](https://codesandbox.io/s/v-smooth-scroll-demo-forked-8ksi3x?file=/src/components/HelloWorld.vue) and used the Composition API instead of the Options API that your demo was using.

Please let me know if you need more info, I'll be more than happy to provide it.

Thank you!
